import * as T from 'three';
import type {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import type {Pagoda} from './geometry';
import type {View} from './camera';
type Options={pagoda:Pagoda;camera:T.PerspectiveCamera;controls:OrbitControls;invalidate:()=>void;setView:(v:View)=>void;explode:(v:boolean)=>void;pause:()=>void;separation:(amount:number)=>void};
const dict={title:['构造研习','構造研習','Structure study'],toggle:['探索构造','探索構造','Explore'],close:['返回展陈','返回展陳','Exhibition'],intro:['从整塔，走进一榫一卯。','從整塔，走進一榫一卯。','From the monument to its members.'],floor:['观察楼层','觀察樓層','Storey'],all:['整座木塔','整座木塔','Whole pagoda'],roof:['显示屋面','顯示屋面','Show roofs'],wall:['显示围护','顯示圍護','Show enclosure'],separate:['展示性分层','展示性分層','Display separation'],focus:['细节定位','細節定位','Detail views'],inner:['二层内槽梁架','二層內槽梁架','Inner frame · storey 2'],bracket:['二层檐下斗拱','二層簷下斗栱','Eave brackets · storey 2'],finial:['塔刹与铁仰莲','塔剎與鐵仰蓮','Finial & iron lotus'],note:['当前研究模型 · 构件与连接仍有近似。分层不代表真实拆卸顺序。','目前研究模型 · 構件與連接仍有近似。分層不代表真實拆卸順序。','Research model with estimated members and joints. Separation is illustrative, not a dismantling sequence.'],cut:['剖看内槽','剖看內槽','Cutaway'],cutnote:['剖切不封口，仅用于查看内部。','剖切不封口，僅用於查看內部。','Open clipping surfaces for inspection only.']} as const;
const tr=(k:keyof typeof dict)=>dict[k][document.documentElement.lang==='en'?2:document.documentElement.lang==='zh-TW'?1:0];
export function installExplorer(o:Options){
 const {pagoda,camera,controls,invalidate}=o;let opened=false,floor=-1,roof=true,wall=true,cut=false;const clip=new T.Plane(new T.Vector3(0,0,-1),0);
 const toggle=document.createElement('button');toggle.id='explore-toggle';toggle.className='text-button';toggle.setAttribute('aria-expanded','false');document.querySelector('.header-actions')!.prepend(toggle);
 const pane=document.createElement('section');pane.className='ui explorer';pane.hidden=true;pane.id='explorer';pane.setAttribute('aria-label','Structure study');document.querySelector('#app')!.append(pane);toggle.setAttribute('aria-controls','explorer');
 const meshes:T.Mesh[]=[];pagoda.root.traverse(n=>{if(n instanceof T.Mesh)meshes.push(n)});
 function apply(){pagoda.floorGroups.forEach((g,i)=>g.visible=floor<0||floor===i);for(const m of meshes){const c=m.userData.category;m.visible=(!['roof'].includes(c)||roof)&&(c!=='enclosure'||wall);for(const mat of Array.isArray(m.material)?m.material:[m.material]){mat.clippingPlanes=cut?[clip]:[];mat.clipShadows=true;}}invalidate();}
 function frame(box:T.Box3,dir=new T.Vector3(.6,.25,1),fill=.78){const size=box.getSize(new T.Vector3()),target=box.getCenter(new T.Vector3());const distance=Math.max(size.y,size.x/camera.aspect,size.z)*.5/Math.tan(T.MathUtils.degToRad(camera.fov/2))/fill;controls.enableDamping=false;controls.update();controls.target.copy(target);camera.position.copy(target).addScaledVector(dir.normalize(),Math.max(5,distance));controls.minDistance=1;controls.maxDistance=350;controls.update();controls.enableDamping=true;invalidate();}
 function visibleFrame(){pagoda.root.updateMatrixWorld(true);const b=new T.Box3();pagoda.floorGroups.forEach((g,i)=>{if(floor<0||floor===i)b.union(new T.Box3().setFromObject(g));});frame(b);}
 function focus(key:string){o.pause();o.explode(false);floor=key==='finial'?4:1;roof=key==='finial';wall=false;cut=false;apply();
  if(key==='finial'){const b=new T.Box3();meshes.filter(m=>m.userData.category==='finial').forEach(m=>b.union(new T.Box3().setFromObject(m)));frame(b,new T.Vector3(.5,.06,1));}
  else if(key==='inner'){const target=new T.Vector3(2.5,23.3,6);frame(new T.Box3().setFromCenterAndSize(target,new T.Vector3(8,6,7)),new T.Vector3(.6,.35,1));}
  else {frame(new T.Box3().setFromCenterAndSize(pagoda.detailTarget,new T.Vector3(8,6,7)),new T.Vector3(.2,-.15,1));}
  render();
 }
 function render(){toggle.textContent=tr(opened?'close':'toggle');toggle.setAttribute('aria-expanded',String(opened));pane.innerHTML=`<div class="explorer-heading"><span>02 / ${tr('title')}</span><button id="study-close" aria-label="${tr('close')}">×</button></div><p class="explorer-intro">${tr('intro')}</p><label class="study-label">${tr('floor')}<select id="study-floor"><option value="-1">${tr('all')}</option>${[1,2,3,4,5].map(n=>`<option value="${n-1}" ${floor===n-1?'selected':''}>${document.documentElement.lang==='en'?'Storey ':''}${n}${document.documentElement.lang==='en'?'':document.documentElement.lang==='zh-TW'?' 層':' 层'}</option>`).join('')}</select></label><div class="study-switches"><button id="study-roof" aria-pressed="${roof}">${tr('roof')}</button><button id="study-wall" aria-pressed="${wall}">${tr('wall')}</button><button id="study-cut" aria-pressed="${cut}">${tr('cut')}</button></div><label class="study-label">${tr('separate')}<input id="study-gap" type="range" min="0" max="1" step=".01" value="${pagoda.floorGroups[4].position.y/28}"></label><p class="study-label">${tr('focus')}</p><div class="study-details"><button data-focus="bracket">01 <span>${tr('bracket')}</span>↗</button><button data-focus="inner">02 <span>${tr('inner')}</span>↗</button><button data-focus="finial">03 <span>${tr('finial')}</span>↗</button></div><p class="study-note">${tr('note')} ${cut?tr('cutnote'):''}</p>`;
  pane.querySelector<HTMLSelectElement>('#study-floor')!.value=String(floor);
 }
 function open(on:boolean){o.pause();opened=on;pane.hidden=!on;document.body.classList.toggle('studying',on);render();requestAnimationFrame(()=>requestAnimationFrame(()=>{if(on)visibleFrame();else{o.setView('hero');toggle.focus();}}));}
 toggle.onclick=()=>open(!opened);
 pane.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest('button');if(!b)return;if(b.id==='study-close')open(false);if(b.id==='study-roof'){roof=!roof;apply();render();pane.querySelector<HTMLButtonElement>('#'+b.id)?.focus();}if(b.id==='study-wall'){wall=!wall;apply();render();pane.querySelector<HTMLButtonElement>('#'+b.id)?.focus();}if(b.id==='study-cut'){cut=!cut;apply();render();}if(b.dataset.focus)focus(b.dataset.focus);});
 pane.addEventListener('change',e=>{if((e.target as HTMLElement).id==='study-floor'){floor=Number((e.target as HTMLSelectElement).value);apply();visibleFrame();}});
 pane.addEventListener('input',e=>{if((e.target as HTMLElement).id==='study-gap'){const amount=Number((e.target as HTMLInputElement).value);pagoda.floorGroups.forEach((g,i)=>g.position.y=i*7*amount);o.pause();o.separation(amount);visibleFrame();}});
 const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'&&opened&&!document.querySelector('dialog[open]'))open(false);};window.addEventListener('keydown',onKey);const observer=new MutationObserver(render);observer.observe(document.documentElement,{attributes:true,attributeFilter:['lang']});render();
 const clearIsolation=()=>{floor=-1;roof=wall=true;cut=false;apply();render();};
 return {refresh:apply,isOpen:()=>opened,clearIsolation,reset:()=>{clearIsolation();open(false);},open,focus,dispose:()=>{observer.disconnect();window.removeEventListener('keydown',onKey);}};
}
