import {bindLanguage, t, rendering} from './i18n';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {ARCH} from './config';import {materials} from './materials';import {buildPagoda} from './geometry';import {environment} from './environment';import {cameras, type View} from './camera';import {exportImage,download} from './export';import {mount} from './ui';import './style.css';
import './layout.css';
mount();bindLanguage();await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));const $=<E extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as E;
const state={clay:new URLSearchParams(location.search).has('clay'),evening:false,explode:false,orbit:false,hidden:false,quality:innerWidth<760?'low':'high'};
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let renderer:T.WebGLRenderer;
try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{$('loading').textContent=t('当前浏览器无法启用 WebGL 2。请使用支持硬件加速的现代浏览器重新打开。');throw new Error('WebGL unavailable');}
renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;$('stage').appendChild(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label',t('交互式木塔。方向键转动，加减号缩放。'));
const scene=new T.Scene();const camera=new T.PerspectiveCamera(31,1,.15,1000);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.12;controls.enablePan=false;controls.minPolarAngle=.005;controls.maxPolarAngle=Math.PI*.53;controls.rotateSpeed=.45;controls.zoomSpeed=.7;controls.autoRotateSpeed=.25;
const palette=materials();const started=performance.now();const pagoda=buildPagoda(palette);const geometryBuildMs=performance.now()-started;scene.add(pagoda.root);const env=environment(scene,renderer);const cam=cameras(camera,controls,pagoda);
const originals=new Map<T.Mesh,T.Material|T.Material[]>();pagoda.root.traverse(o=>{if(o instanceof T.Mesh)originals.set(o,o.material);});
function setClay(on:boolean){state.clay=on;for(const [mesh,material]of originals)mesh.material=on?palette.clay:material;$('clay').setAttribute('aria-pressed',String(on));invalidate();}
let frames=0,last=0,active=false,noticeTimer:number,exporting=false;
function draw(t:number){frames=0;const dt=last?Math.min(.04,(t-last)/1000):1/60;last=t;controls.autoRotate=state.orbit;const changed=controls.update(dt);renderer.render(scene,camera);if(state.orbit||active||changed)invalidate();}
function invalidate(){if(!frames)frames=requestAnimationFrame(draw);}
function notice(message:string){$('notice').textContent=message;$('notice').classList.add('visible');clearTimeout(noticeTimer);noticeTimer=window.setTimeout(()=>$('notice').classList.remove('visible'),5000);}
function quality(){renderer.setPixelRatio(state.quality==='low'?1:Math.min(devicePixelRatio,1.75));env.key.shadow.mapSize.setScalar(state.quality==='low'?1024:2048);env.key.shadow.map?.dispose();env.key.shadow.map=null;resize();}
function resize(){const r=$('stage').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;if(innerWidth>760&&!state.hidden)camera.setViewOffset(r.width,r.height,-(innerWidth<=1000?90:130),0,r.width,r.height);else camera.clearViewOffset();camera.updateProjectionMatrix();invalidate();}
function setView(view:View){document.body.classList.toggle("detail-view",view==="detail");cam.preset(view);document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));invalidate();}
function orbit(on:boolean){state.orbit=on;$('orbit').setAttribute('aria-pressed',String(on));$('orbit').querySelector('span')!.textContent=t(on?'开启':'关闭');invalidate();}
function explode(on:boolean){state.explode=on;pagoda.floorGroups.forEach((g,i)=>g.position.y=on?i*ARCH.explodeGap:0);$('explode').setAttribute('aria-pressed',String(on));$('separation').hidden=!on;setView('hero');}
function hide(on:boolean){state.hidden=on;document.body.classList.toggle('ui-hidden',on);$('restore').hidden=!on;$('settings-panel').hidden=true;$('settings').setAttribute('aria-expanded','false');resize();if(on)$('restore').focus();}
$('clay').onclick=()=>setClay(!state.clay);$('evening').onclick=()=>{state.evening=!state.evening;env.set(state.evening);$('evening').setAttribute('aria-pressed',String(state.evening));document.body.classList.toggle('evening',state.evening);invalidate();};$('explode').onclick=()=>explode(!state.explode);$('orbit').onclick=()=>orbit(!state.orbit);$('hide').onclick=()=>hide(true);$('restore').onclick=()=>hide(false);
$('settings').onclick=()=>{const open=$('settings-panel').hidden;$('settings-panel').hidden=!open;$('settings').setAttribute('aria-expanded',String(open));};$('quality').onchange=()=>{state.quality=$<HTMLSelectElement>('quality').value;quality();};
$('reset').onclick=()=>{$('notice').classList.remove('visible');orbit(false);setClay(false);state.evening=false;env.set(false);document.body.classList.remove('evening');$('evening').setAttribute('aria-pressed','false');explode(false);hide(false);state.quality=innerWidth<760?'low':'high';$<HTMLSelectElement>('quality').value=state.quality;quality();};
document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view as View));
const dialog=$<HTMLDialogElement>('source-dialog');$('sources').onclick=()=>dialog.showModal();$('close-sources').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
async function save(width:number,height:number){if(exporting)return;exporting=true;orbit(false);$('export4k').setAttribute('disabled','');$('exporthd').setAttribute('disabled','');notice(rendering(width,height));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
 try{const blob=await exportImage(renderer,scene,cam.exportCamera(width/height),width,height);download(blob,`${t('木构千年')}-${cam.current}-${width}x${height}.png`);notice(t('图片已导出，已恢复交互画面。'));}catch(e){notice(t((e as Error).message)+' '+t('可在更多中选择较低分辨率。'));}finally{exporting=false;$('export4k').removeAttribute('disabled');$('exporthd').removeAttribute('disabled');invalidate();}}
$('export4k').onclick=()=>void save(3840,2160);$('exporthd').onclick=()=>void save(1920,1080);
controls.addEventListener('start',()=>{active=true;if(state.orbit)orbit(false);invalidate();});controls.addEventListener('end',()=>{active=false;invalidate();});controls.addEventListener('change',invalidate);
renderer.domElement.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key)){e.preventDefault();orbit(false);const s=new T.Spherical().setFromVector3(camera.position.clone().sub(controls.target));if(e.key==='ArrowLeft')s.theta-=.08;if(e.key==='ArrowRight')s.theta+=.08;if(e.key==='ArrowUp')s.phi-=.06;if(e.key==='ArrowDown')s.phi+=.06;if(e.key==='-'||e.key==='+'||e.key==='=')s.radius*=e.key==='-'?1.08:.92;s.phi=T.MathUtils.clamp(s.phi,controls.minPolarAngle,controls.maxPolarAngle);s.radius=T.MathUtils.clamp(s.radius,controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).add(new T.Vector3().setFromSpherical(s));controls.update();invalidate();}});
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h'&&!dialog.open&&!['INPUT','SELECT','TEXTAREA'].includes((e.target as HTMLElement).tagName))hide(!state.hidden);if(e.key==='Escape'){$('settings-panel').hidden=true;$('settings').setAttribute('aria-expanded','false');}});
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();orbit(false);$('loading').hidden=false;$('loading').textContent=t('图形上下文已丢失，请刷新页面恢复展陈。');});
document.addEventListener('visibilitychange',()=>{if(document.hidden){orbit(false);cancelAnimationFrame(frames);frames=0;}else invalidate();});reduced.addEventListener('change',()=>{if(reduced.matches)orbit(false);});
new ResizeObserver(resize).observe($('stage'));quality();setClay(state.clay);setView('hero');$('loading').hidden=true;$<HTMLSelectElement>('quality').value=state.quality;
const debug={state,renderer,scene,camera,controls,pagoda,setView,setClay,explode,orbit,hide,save,render:()=>renderer.render(scene,camera),exportBlob:()=>exportImage(renderer,scene,cam.exportCamera(16/9)),metrics:()=>({three:T.REVISION,geometryBuildMs,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,pixelRatio:renderer.getPixelRatio(),size:renderer.getSize(new T.Vector2()).toArray(),bounds:cam.bounds().getSize(new T.Vector3()).toArray(),webgl:renderer.getContext().getParameter(renderer.getContext().VERSION),reducedMotion:reduced.matches})};
(window as any).__pagoda=debug;(window as any).__ready=true;
window.addEventListener('pagehide',()=>{controls.dispose();cancelAnimationFrame(frames);const geos=new Set<T.BufferGeometry>(),mats=new Set<T.Material>(),maps=new Set<T.Texture>();scene.traverse(o=>{if(o instanceof T.Mesh){geos.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(x=>mats.add(x));if(o instanceof T.InstancedMesh)o.dispose();}});Object.values(palette).forEach(x=>mats.add(x));mats.forEach(mat=>{Object.values(mat).forEach(v=>{if(v instanceof T.Texture)maps.add(v)});mat.dispose();});maps.forEach(x=>x.dispose());geos.forEach(x=>x.dispose());renderer.dispose();});
