import {SOURCES} from './config';
import {VIEWS} from './camera';
export function mount(){document.querySelector('#app')!.innerHTML=`
<div id="stage" aria-label="应县木塔三维展陈。拖动旋转，滚轮或双指缩放。"></div>
<header class="ui masthead"><a class="brand" href="./" aria-label="木构千年首页"><span class="seal">木</span><span>木构千年<span class="brand-en">A MILLENNIUM IN TIMBER</span></span></a><div class="header-actions"><select id="language" aria-label="语言 / Language"><option value="zh-CN">简体中文</option><option value="zh-TW">繁體中文</option><option value="en">English</option></select><button id="sources" class="text-button">资料与说明 <span>↗</span></button></div></header>
<aside class="ui caption"><p class="eyebrow">山西 · 应县 &nbsp; / &nbsp; 辽代木构</p><h1>应县木塔</h1><p class="english">Yingxian<br>Wooden Pagoda</p><div class="rule"></div><p class="verse">一榫一卯，<br>撑起千年。</p><dl><div><dt>肇建</dt><dd>1056 <small>年</small></dd></div><div><dt>形制</dt><dd class="shape">五层六檐 · 八角</dd></div></dl><p class="scope">基于公开资料的外观视觉复刻<br>数字展陈环境 · 非测绘模型</p></aside>
<div class="ui right-mark"><span>佛宫寺释迦塔</span><i></i><span>01 / 木构遗产</span></div>
<div class="ui view-nav" role="group" aria-label="预设视角"><span class="nav-label">观 察</span>${VIEWS.map(([key,label],i)=>`<button data-view="${key}" aria-pressed="${i===0}"><span class="view-number">0${i+1}</span>${label}</button>`).join('')}</div>
<footer class="ui bottom"><div class="hint"><span class="dot"></span> 实时三维 <span class="hint-detail">&nbsp; / &nbsp; 拖动旋转 · 滚动缩放</span></div><div class="tools"><button id="clay" aria-pressed="false">白模</button><button id="evening" aria-pressed="false">傍晚</button><button id="explode" aria-pressed="false">楼层展开</button><button id="settings" aria-expanded="false">更多 <span>＋</span></button><button id="reset" aria-label="复位相机与所有展陈设置">复位 ↺</button></div></footer>
<section id="settings-panel" class="ui settings" hidden aria-label="展陈设置"><button id="orbit" aria-pressed="false">自动环绕 <span>关闭</span></button><button id="hide">隐藏界面 <span>H</span></button><label>画面质量 <select id="quality"><option value="high">精细</option><option value="low">流畅</option></select></label><div class="export-heading">保存当前视角 · 不含界面</div><button id="export4k">导出 4K PNG <span>↗</span></button><button id="exporthd">导出 1920 × 1080 <span>↗</span></button></section>
<button id="restore" hidden>显示界面 <span>H</span></button><div id="notice" role="status" aria-live="polite"></div><div id="separation" class="ui separation" hidden>展示性分层 · 不代表真实拆卸顺序</div><div id="loading" role="status">正在生成木构与屋面几何…</div>
<dialog id="source-dialog"><div class="dialog-head"><span>研究档案 / 01</span><button id="close-sources" aria-label="关闭资料与说明">关闭 ×</button></div><h2>有所依据，<br>也有所保留。</h2><p>这一版呈现应县木塔的建筑外观。轮廓以八角平面、五层六檐、首层重檐及上层柱廊为依据，细部经过适合实时观看的简化。</p><h3>尺度与近似范围</h3><p>总高采用官方申报资料的 <strong>67.31 米</strong>，从展示地面至塔刹顶，包含台基。研究院另记录 2011 年从正南地面测得 <strong>65.838 米</strong>；两者不能作为同一测量基准直接互换。底层含副阶面阔 <strong>30.27 米</strong>，资料未在该段明示对边或对角，本模型暂按对角跨度处理。</p><p>逐层标高、收分、出檐、曲率、台基、柱径与斗拱细部均为参数化视觉近似，未经完整测绘图核定。没有复原全部暗层内构、榫卯、佛像、原匾书法、彩画图样和现状倾斜。为保持无缝展陈地面，本版省略突出于八角台基之外的方形下台基层。八块主要匾额按南北朝向与明层布置，释迦塔采用竖匾。匾额尺寸与色彩为视觉近似，系统楷体字面不等于原匾书法。展开仅为展示性分层。</p><h3>参考索引</h3>${SOURCES.map((s,i)=>`<article><a href="${s.url}" target="_blank" rel="noopener noreferrer"><small>0${i+1}</small> ${s.title} ↗</a><p>${s.author}</p><p>${s.supports}</p><p class="rights">${s.rights}</p></article>`).join('')}<h3>数字展陈与资源</h3><p>暖灰背景、地面及日光/傍晚照明为展陈设计，不复原寺院周边。所有三维几何与纹理在本地程序生成，固定种子；没有用整幅建筑照片替代模型。字体调用设备自带宋体与无衬线字体，不分发商业字体。</p><p class="rights">木构千年 · 第一版 / 外观视觉复刻<br>不用于测绘、文物修复或结构工程判断。</p></dialog>`;}
