import {chromium} from '@playwright/test';import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||chromium.executablePath(),args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[],requests=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('requestfailed',r=>requests.push(r.url()));
await page.goto('http://127.0.0.1:5173/');await page.waitForFunction(()=>window.__ready);await page.waitForTimeout(500);
async function shot(name){await page.waitForTimeout(300);await page.screenshot({path:`artifacts/${name}.png`});}
await shot('desktop');
for(const [key,label]of [['low','05低机位'],['detail','06斗拱近景']]){await page.getByRole('button',{name:label,exact:true}).click();await shot(key);}
await page.getByRole('button',{name:'楼层展开',exact:true}).click();await shot('exploded');checks.push({name:'exploded offsets',value:await page.evaluate(()=>window.__pagoda.pagoda.floorGroups.map(g=>g.position.y))});
await page.getByRole('button',{name:'楼层展开',exact:true}).click();checks.push({name:'restored offsets',value:await page.evaluate(()=>window.__pagoda.pagoda.floorGroups.map(g=>g.position.y))});
await page.getByRole('button',{name:'傍晚',exact:true}).click();await shot('evening');await page.getByRole('button',{name:'傍晚',exact:true}).click();
await page.getByRole('button',{name:'更多 ＋',exact:true}).click();await page.getByRole('button',{name:'自动环绕 关闭',exact:true}).click();const p1=await page.evaluate(()=>window.__pagoda.camera.position.toArray());await page.waitForTimeout(900);const p2=await page.evaluate(()=>window.__pagoda.camera.position.toArray());checks.push({name:'orbit moves',value:JSON.stringify(p1)!==JSON.stringify(p2)});
await page.mouse.move(900,500);await page.mouse.down();await page.mouse.move(1050,520,{steps:10});await page.mouse.up();await page.waitForTimeout(300);checks.push({name:'drag pauses orbit',value:await page.evaluate(()=>!window.__pagoda.state.orbit)});
await page.getByRole('button',{name:'复位相机与所有展陈设置'}).click();await page.getByRole('button',{name:'更多 ＋',exact:true}).click();const sizeBefore=await page.evaluate(()=>({pos:window.__pagoda.camera.position.toArray(),size:window.__pagoda.renderer.getSize({set(x,y){this.x=x;this.y=y;return this}})}));
const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'导出 4K PNG ↗',exact:true}).click();const d=await downloading;await d.saveAs('artifacts/木构千年-主视觉-3840x2160.png');await page.waitForTimeout(300);const sizeAfter=await page.evaluate(()=>({pos:window.__pagoda.camera.position.toArray(),size:window.__pagoda.renderer.getSize({set(x,y){this.x=x;this.y=y;return this}})}));checks.push({name:'export preserves camera and size',value:sizeBefore.pos.every((v,i)=>Math.abs(v-sizeAfter.pos[i])<1e-6)&&sizeBefore.size.x===sizeAfter.size.x&&sizeBefore.size.y===sizeAfter.size.y,before:sizeBefore,after:sizeAfter});await shot('after-export');
await page.getByRole('button',{name:'隐藏界面 H',exact:true}).click();await shot('clean-view');await page.getByRole('button',{name:'显示界面 H',exact:true}).click();
await page.getByRole('button',{name:'资料与说明 ↗',exact:true}).click();checks.push({name:'source dialog',value:await page.locator('dialog').isVisible()});await page.keyboard.press('Escape');
const perf=await page.evaluate(async()=>{const p=window.__pagoda;p.orbit(true);const times=[];let t=performance.now();for(let i=0;i<90;i++){await new Promise(requestAnimationFrame);const n=performance.now();times.push(n-t);t=n;}p.orbit(false);times.sort((a,b)=>a-b);const gl=p.renderer.getContext();const ext=gl.getExtension('WEBGL_debug_renderer_info');return {medianFrameMs:times[45],p95FrameMs:times[85],gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'unavailable',metrics:p.metrics()};});
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'复位相机与所有展陈设置'}).click();await shot('mobile');checks.push({name:'mobile no overflow',value:await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)});
await page.getByRole('button',{name:'更多 ＋',exact:true}).click();await shot('mobile-controls');await page.selectOption('#quality','low');checks.push({name:'low quality DPR',value:await page.evaluate(()=>window.__pagoda.renderer.getPixelRatio())});
await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.waitForFunction(()=>window.__ready);checks.push({name:'reduced motion initial orbit off',value:await page.evaluate(()=>!window.__pagoda.state.orbit)});
await fs.writeFile('artifacts/validation.json',JSON.stringify({testedAt:new Date().toISOString(),browser:await browser.version(),viewport:{width:1440,height:1000},mobileViewport:{width:390,height:844},errors,requests,checks,perf},null,2));console.log(JSON.stringify({errors,requests,checks,perf},null,2));await browser.close();
